# baseURL = "https://mikects.com"
languageCode = "en"
defaultContentLanguage = "en"

title = "Mike Coates"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  # name = "Mike Coates"
  headline = "Dad, gamer, housecarl, astrophotographer, astronomer, technology consultant."
  image = "img/MyMug_2024_400x400_circ.png"  # path relative to static directory

  links = [
    { linkedin = "https://www.linkedin.com/in/mike-c-922746303/" },
    { signal = { href = "https://signal.me/#eu/lkSBORf-VTemAQTBW55j-t-guueK_M5WEZCePMHJKI6Hh1sxTW9IJYKehrFatZ0N" , text = "Signal"}},
    { telegram = "https://t.me/mike_coates_astro" },
    { mcastro-space = {href = "https://mcastro.space/" , text = "Astrophotography Gallery" }},
    { astrobin = { href = "https://www.astrobin.com/users/MCAstro/" , text = "AstroBin"}},
    { instagram = "https://www.instagram.com/mcastro.space/" },
    { facebook = "https://www.facebook.com/MCAstro.space" },
    { mastodon = "https://universeodon.com/@mcastro" },
    { threads = "https://www.threads.net/@mcastro.space" },
    { youtube = "https://www.youtube.com/@MCAstroSpace" },
    { untappd = { href = "https://untappd.com/user/FixieR1der" , text = "Untappd"}},
    # { email = "mailto:hello@your_domain.com" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },
    # { bluesky = "https://bsky.app/profile/username" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/username" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { keybase = "https://keybase.io/fixierider" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "https://x.com/username" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"